import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { allow, allowedOrigin, clean, json, verifiedUser } from "./shared.js";

function paragraph(text, options = {}) {
  return new Paragraph({ children: [new TextRun({ text: clean(text, 1500), ...options })], spacing: { after: 100 } });
}

export default async function handler(req, res) {
  if (!allowedOrigin(req, res)) return json(res, 403, { error: "This origin is not allowed." });
  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "POST") return json(res, 405, { error: "POST only" });
  const auth = await verifiedUser(req);
  if (!auth) return json(res, 401, { error: "Sign in before exporting a kit." });
  if (!allow(`export:${auth.user.id}`, 8)) return json(res, 429, { error: "Please wait before another export." });
  const candidate = req.body?.candidate || {};
  const kit = req.body?.kit || {};
  const job = req.body?.job || {};
  const selected = Array.isArray(req.body?.selectedEvidence) ? req.body.selectedEvidence : [];
  try {
    const sections = [
      paragraph(candidate.full_name || "Candidate", { bold: true, size: 30 }),
      paragraph([candidate.target_role, candidate.email, candidate.portfolio].filter(Boolean).join("  |  "), { color: "4B5563" }),
      new Paragraph({ text: "SUMMARY", heading: HeadingLevel.HEADING_2 }),
      paragraph(kit.summary || "Review this summary and keep only facts you can support."),
      new Paragraph({ text: "SELECTED EXPERIENCE", heading: HeadingLevel.HEADING_2 }),
      ...selected.flatMap((item) => [paragraph(item.title || "Experience", { bold: true }), paragraph(item.bullet || item.details || "")]),
      new Paragraph({ text: "ROLE FOCUS", heading: HeadingLevel.HEADING_2 }),
      paragraph(`${clean(job.title, 160)} · ${clean(job.company, 160)}`),
      paragraph("Generated by RoleReady from user-confirmed evidence. Review before sending." , { italics: true, color: "6B7280" })
    ];
    const document = new Document({ sections: [{ properties: {}, children: sections }] });
    const buffer = await Packer.toBuffer(document);
    const safeName = clean(job.company || "role-ready", 80).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase();
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", `attachment; filename="${safeName || "role-ready"}-application-kit.docx"`);
    return res.status(200).send(buffer);
  } catch (error) {
    return json(res, 500, { error: "The DOCX export could not be created." });
  }
}
